"""add tag columns to reviewer and reviewee

Revision ID: 20f98ca93cb9
Revises: cf257e38b575
Create Date: 2026-04-28 06:49:06.070798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f98ca93cb9'
down_revision: Union[str, Sequence[str], None] = 'cf257e38b575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tag_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tag_3', sa.String(length=255), nullable=True))

    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tag_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tag_3', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.drop_column('tag_3')
        batch_op.drop_column('tag_2')
        batch_op.drop_column('tag_1')

    with op.batch_alter_table('reviewees', schema=None) as batch_op:
        batch_op.drop_column('tag_3')
        batch_op.drop_column('tag_2')
        batch_op.drop_column('tag_1')

    # ### end Alembic commands ###
